<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Title>$(AssemblyName)</Title>
    <Version>1.0.7-rc1</Version>
    <Authors>TheColdWorld</Authors>
    <Company>Null</Company>
    <Product>Null</Product>
    <Description>WebSocket support for TheColdWorld.Utils</Description>
    <PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/TheColdWorld/TheColdWorld.Utils.WebSocket.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/TheColdWorld/TheColdWorld.Utils.WebSocket</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TheColdWorld.Utils" Version="1.0.6" />
  </ItemGroup>

</Project>
