using System.Net;
using System.Net.WebSockets;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json.Nodes;
using System.Text.Unicode;
using TheColdWorld.Utils;
using TheColdWorld.Utils.socket;
using TheColdWorld.Utils.WebSocket;
//Generated by Deepseek
namespace ConsoleDebug
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            Logging.OnLogging += (level, time, message, threadName, exception) =>
                Console.WriteLine($"[{time:yyyy-MM-dd HH:mm:ss}][{(string.IsNullOrWhiteSpace(threadName) ? "" : $"{threadName}/")}{level}] {message}{(exception == null ? "" : $"\n{exception}")}");

            int port = 25565;
            CancellationTokenSource cts = new();

            // 启动 WebSocket 服务器
            HttpListener listener = new();
            listener.Prefixes.Add($"http://localhost:{port}/");
            listener.Start();
            Console.WriteLine($"[Server] WebSocket server started at ws://localhost:{port}/");

            _ = Task.Run(async () =>
            {
                while (!cts.IsCancellationRequested)
                {
                    try
                    {
                        var context = await listener.GetContextAsync();
                        if (context.Request.IsWebSocketRequest)
                        {
                            var wsContext = await context.AcceptWebSocketAsync(null);
                            _ = WebSocketServerController.Instance.ProcessClientAsync(wsContext.WebSocket, cts.Token);
                        }
                        else
                        {
                            context.Response.StatusCode = 400;
                            context.Response.Close();
                        }
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        Console.WriteLine($"[Server] Accept error: {ex.Message}");
                    }
                }
            });

            await Task.Delay(500);

            var uri = new Uri($"ws://localhost:{port}/");
            var client1 = new WebSocketClient(uri, (data, id, sendToRemote) =>
            {
                Console.WriteLine($"[Debug] Client1 received packet (ID:{id}) : {data.ToJsonString(new() { Encoder = JavaScriptEncoder.Create(UnicodeRanges.All) })}");
            }, "Client1");
            var client2 = new WebSocketClient(uri, (data, id, sendToRemote) =>
            {
                Console.WriteLine($"[Debug] Client2 received packet (ID:{id}) : {data.ToJsonString(new() { Encoder = JavaScriptEncoder.Create(UnicodeRanges.All) })}");
            }, "Client2");

            await Task.Delay(1000);

            Console.WriteLine("\n--- Test 1: client1.Send(new TestPacket()) -> should succeed ---");
            client1.Send(new TestPacket());

            Console.WriteLine("\n--- Test 2: client1.Send(new TestPacket2()) -> should throw ---");
            try { client1.Send(new TestPacket2()); }
            catch (ArgumentException ex) { Console.WriteLine($"[Debug] Successfully caught expected exception: {ex.Message}"); }

            Console.WriteLine("\n--- Test 3: server broadcast TestPacket2 (ClientBind) -> should succeed ---");
            await WebSocketServerController.Instance.BroadCastAsync(new TestPacket2());

            Console.WriteLine("\n--- Test 4: server broadcast TestPacket (ServerBind) -> should throw ---");
            try { await WebSocketServerController.Instance.BroadCastAsync(new TestPacket()); }
            catch (ArgumentException ex) { Console.WriteLine($"[Debug] Successfully caught expected exception: {ex.Message}"); }

            Console.WriteLine("\n--- Additional: client2.Send(new TestPacket()) ---");
            client2.Send(new TestPacket());
            Console.WriteLine("\n--- Additional: connection failed ---");
            try
            {
               using WebSocketClient client = new(new("ws://localhost:25554"), (a, b, c) => { });
            }
            catch(WebSocketException wse)
            {
                Console.WriteLine($"success:{wse}");
            }
            catch (Exception e)
            {
                Console.WriteLine($"failed:{e}");
            }
            Console.WriteLine("\nPress any key to exit...");
            Console.ReadKey(true);

            cts.Cancel();
            client1.Dispose();
            client2.Dispose();
            listener.Stop();
        }
    }

    class TestPacket : IPacket
    {
        public PacketBindSide PacketBindSide => PacketBindSide.ServerBind;
        public Identifier Identifier => new("test", "serverbind");
        public JsonObject Write() => new() { ["int"] = 1, ["str"] = "客户端：我的包啊" };
    }

    class TestPacket2 : IPacket
    {
        public PacketBindSide PacketBindSide => PacketBindSide.ClientBind;
        public Identifier Identifier => new("test", "clientbound");
        public JsonObject Write() => new() { ["int"] = 2, ["str"] = "服务端：我的包啊" };
    }
}